services:
  # --- API GATEWAY ---
  gateway:
    restart: always

  # --- USER SERVICE ---
  user-service:
    image: ghcr.io/renoaji/ecommerce-microservice/user-service:main
    restart: always

  user-db:
    ports: []
    restart: always

  # --- PRODUCT SERVICE ---
  product-service:
    image: ghcr.io/renoaji/ecommerce-microservice/product-service:main
    restart: always
    # No local volumes for small image

  product-db:
    ports: []
    restart: always

  # --- CART SERVICE ---
  cart-service:
    image: ghcr.io/renoaji/ecommerce-microservice/cart-service:main
    restart: always

  redis:
    restart: always

  consul:
    restart: always
    command: [ "agent", "-dev", "-log-level=warn", "-client=0.0.0.0" ]

  # --- ORDER SERVICE ---
  order-service:
    image: ghcr.io/renoaji/ecommerce-microservice/order-service:main
    restart: always

  order-db:
    ports: []
    restart: always

  # --- PAYMENT SERVICE ---
  payment-service:
    image: ghcr.io/renoaji/ecommerce-microservice/payment-service:main
    restart: always

  payment-db:
    ports: []
    restart: always

  # --- DELIVERY SERVICE ---
  delivery-service:
    image: ghcr.io/renoaji/ecommerce-microservice/delivery-service:main
    restart: always

  delivery-db:
    ports: []
    restart: always

  # ELK STACK
  elasticsearch:
    restart: always

  logstash:
    restart: always

  kibana:
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  filebeat:
    restart: always
