input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  mutate{
    remove_field => ["message"]
  }

  mutate {
    strip => ["log"]
  }

  if [log] =~ /^\{/ {
    json {
      source => "log"
    }
  }

  mutate {
    rename => { "M" => "message" }
  }

  if [service] != "api-gateway" {
    mutate {
      rename => { "C" => "caller" }
      gsub => ["latency", "[a-zµ]+$", ""]
      convert => { "latency" => "float" }
    }
  }

  date {
    match => ["T", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["timestamp", "time", "T"]
  }

  if [service] == "api-gateway" {
    mutate {
      rename => { "LAT" => "latency" }
      rename => { "B" => "bytes_sent" }
      convert => { "status" => "integer" }
      convert => { "latency" => "float" }
      convert => { "bytes_sent" => "integer" }
    }

    ruby {
      code => "event.set('latency', event.get('latency') * 1000)"
    }
    
    if [status] >= 500 {
      mutate { replace => { "L" => "ERROR" } }
    } else if [status] >= 400 {
      mutate { replace => { "L" => "WARN" } }
    } else {
      mutate { replace => { "L" => "INFO" } }
    }
  }

  if ![L] and [service] != "api-gateway" {
    drop { }
  }

  mutate {
    remove_field => ["log"]
  }

}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservices-%{+YYYY.MM.dd}"
  }

}