name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      services: ${{ steps.filter.outputs.changes }} # Services to build
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            cart-service:
              - cart-service/**
              - libs/**
            order-service:
              - order-service/**
              - libs/**
            payment-service:
              - payment-service/**
              - libs/**
            product-service:
              - product-service/**
              - libs/**
            user-service:
              - user-service/**
              - libs/**
            delivery-service:
              - delivery-service/**
              - libs/**

  # JOB to run tests
  test:
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache-dependency-path: ${{ matrix.service }}/go.sum
      - name: Generate GRPC protocol buffers
        run: |
          protoc --go_out=product-service --go-grpc_out=product-service proto/product.proto
          protoc --go_out=cart-service --go-grpc_out=cart-service proto/product.proto
          protoc --go_out=order-service --go-grpc_out=order-service proto/product.proto
          protoc --go_out=cart-service --go-grpc_out=cart-service proto/cart.proto
          protoc --go_out=order-service --go-grpc_out=order-service proto/cart.proto
          protoc --go_out=payment-service --go-grpc_out=payment-service proto/payment.proto
          protoc --go_out=order-service --go-grpc_out=order-service proto/payment.proto
          protoc --go_out=delivery-service --go-grpc_out=delivery-service proto/delivery.proto
          protoc --go_out=order-service --go-grpc_out=order-service proto/delivery.proto
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./... -cover
      - name: Test integration
        run: go test ./... -tags=integration -count=1
