name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      services: ${{ steps.filter.outputs.changes }} # Services to build
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            cart-service:
              - cart-service/**
              - libs/**
            order-service:
              - order-service/**
              - libs/**
            payment-service:
              - payment-service/**
              - libs/**
            product-service:
              - product-service/**
              - libs/**
            user-service:
              - user-service/**
              - libs/**
            delivery-service:
              - delivery-service/**
              - libs/**

  grpc:
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate GRPC protocol buffers
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          protoc --go_out=. --go-grpc_out=. proto/product.proto
          protoc --go_out=. --go-grpc_out=. proto/cart.proto
          protoc --go_out=. --go-grpc_out=. proto/payment.proto
          protoc --go_out=. --go-grpc_out=. proto/delivery.proto

  # JOB to run tests
  test:
    needs:
      - changes
      - grpc
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache-dependency-path: ${{ matrix.service }}/go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./... -cover
      - name: Test integration
        run: go test ./... -tags=integration -count=1
